# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankMonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankMonitor.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bankMonitor.Bank'),
        ),
        migrations.AddField(
            model_name='trans',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
